apiVersion: apps/v1
kind: ReplicaSet
metadata:
# ReplicaSet example through NGINX
  name: nginx-rs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx-app
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.10
          ports:
            - containerPort: 80
